name: Deploy Container
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Container"]
    types:
      - completed
jobs:
  redeploy_container:
    if: |
      ${{ github.event.workflow_run.conclusion == '' || github.event.workflow_run.conclusion == 'success' }}
    name: Redeploy Container
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy webhook
        env:
          URL: ${{ secrets.DEPLOY_WEBHOOK_URL }}
        run: |
          curl -X POST -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36" $URL